In [1]:
import numpy as np

In [2]:
lambda_mx = np.diag([4.7964,0.3039,0.0063, 0, -0.0067])
print(lambda_mx)

[[ 4.7964  0.      0.      0.      0.    ]
 [ 0.      0.3039  0.      0.      0.    ]
 [ 0.      0.      0.0063  0.      0.    ]
 [ 0.      0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.     -0.0067]]


In [3]:
v_mx = np.array([[0.8869,0.0848,-0.0486,-0.4472,0.0624],
                 [-0.2419,0.4835,0.7019,-0.4472,0.1229],
                 [-0.2157,0.2252,-0.3839,-0.4472,-0.7452],
                 [-0.3049,0.0469,-0.5355,-0.4472,0.6466],
                 [-0.1245,-0.8403,0.2661,-0.4472,-0.0867]])
print(v_mx)

[[ 0.8869  0.0848 -0.0486 -0.4472  0.0624]
 [-0.2419  0.4835  0.7019 -0.4472  0.1229]
 [-0.2157  0.2252 -0.3839 -0.4472 -0.7452]
 [-0.3049  0.0469 -0.5355 -0.4472  0.6466]
 [-0.1245 -0.8403  0.2661 -0.4472 -0.0867]]


In [11]:
print(lambda_mx[:,0:2])

[[4.7964 0.    ]
 [0.     0.3039]
 [0.     0.    ]
 [0.     0.    ]
 [0.     0.    ]]


In [14]:
v_mx @ np.sqrt(lambda_mx)

C:\Users\keyan\AppData\Local\Temp\ipykernel_56736\3686861828.py:1: RuntimeWarning: invalid value encountered in sqrt
  v_mx @ np.sqrt(lambda_mx)


array([[ 1.94237175,  0.0467478 , -0.00385751,  0.        ,         nan],
       [-0.52977757,  0.26653965,  0.05571159,  0.        ,         nan],
       [-0.47239777,  0.12414629, -0.03047112,  0.        ,         nan],
       [-0.66775188,  0.02585462, -0.04250399,  0.        ,         nan],
       [-0.27266353, -0.46323324,  0.02112103,  0.        ,         nan]])

In [15]:
r,c = np.triu_indices(v_mx.shape[0],1)
print(r)
print(c)

[0 0 0 0 1 1 1 2 2 3]
[1 2 3 4 2 3 4 3 4 4]


In [16]:
v_mx[r,c]

array([ 0.0848, -0.0486, -0.4472,  0.0624,  0.7019, -0.4472,  0.1229,
       -0.4472, -0.7452,  0.6466])